"use client";
import {useEffect,useState} from "react";
import type{FormEvent}from"react";
import Link from"next/link";
import{ArrowRight,Mail,MapPin,Send,CheckCircle2,AlertCircle}from"lucide-react";
import{PageHero,SpecLabel}from"@/components/PublicUI";
export default function ContactPage(){const[formToken,setFormToken]=useState("");const[company,setCompany]=useState("");const[submitting,setSubmitting]=useState(false);const[result,setResult]=useState<{ok:boolean;message:string}|null>(null);const[name,setName]=useState("");const[email,setEmail]=useState("");const[message,setMessage]=useState("");useEffect(()=>{fetch("/api/contact").then(r=>r.ok?r.json():null).then(d=>setFormToken(d?.token||"")).catch(()=>{})},[]);async function handleSubmit(e:FormEvent){e.preventDefault();setSubmitting(true);setResult(null);try{const response=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,message,company,token:formToken})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Message could not be sent");setResult({ok:true,message:"Message sent. We will get back to you soon."});setName("");setEmail("");setMessage("")}catch(error:any){setResult({ok:false,message:error.message||"Message could not be sent."})}finally{setSubmitting(false)}}return <div className="public-shell"><PageHero eyebrow="Contact" title="Bring us the" accent="unusual project." copy="For custom requirements, design questions, or work that does not fit the instant quote path, send Dragline the context. For a ready STL or 3MF, the quote tool is usually faster." actions={<Link href="/quote" className="btn-secondary">Go to Quote Tool<ArrowRight size={15}/></Link>}/>
<section className="public-section"><div className="public-container grid gap-8 lg:grid-cols-[1.25fr_.75fr]"><form onSubmit={handleSubmit} className="surface-raised rounded-xl p-6 sm:p-8"><div className="mb-7"><SpecLabel>Project inquiry</SpecLabel><h2 className="heading-md mt-3">Tell us what you need.</h2></div><input type="text" name="company" value={company} onChange={e=>setCompany(e.target.value)} tabIndex={-1} autoComplete="off" className="hidden" aria-hidden="true"/><div className="grid gap-5 sm:grid-cols-2"><Field label="Name"><input className="field" required value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></Field><Field label="Email"><input className="field" required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></Field></div><div className="mt-5"><Field label="Project details"><textarea className="field min-h-40 resize-y" required value={message} onChange={e=>setMessage(e.target.value)} placeholder="Part, quantity, intended use, timing, and any unusual requirements"/></Field></div>{result&&<div role="status" className={`mt-5 flex items-start gap-2 rounded-md border p-3 text-sm ${result.ok?"border-success/30 bg-success/10 text-success":"border-error/30 bg-error/10 text-error"}`}>{result.ok?<CheckCircle2 size={17}/>:<AlertCircle size={17}/>}<span>{result.message}</span></div>}<button type="submit" disabled={submitting||!formToken} className="btn-primary mt-6 disabled:cursor-not-allowed disabled:opacity-50">{submitting?"Sending…":"Send Message"}<Send size={15}/></button></form>
<aside className="space-y-4"><Info icon={<Mail/>} label="Email" value="info@dragline3d.com"/><Info icon={<MapPin/>} label="Location" value="Louisville, Kentucky" copy="Local pickup is available. Shipping options are presented in the order workflow."/><div className="rounded-xl border border-amber/20 bg-amber/[.06] p-6"><SpecLabel>Have a model?</SpecLabel><h3 className="mt-4 font-display text-2xl font-bold">Skip the email queue.</h3><p className="body-copy mt-3">Upload an STL or 3MF to review the model, choose a material, and generate pricing.</p><Link href="/quote" className="btn-quiet mt-4 text-amber">Start a quote<ArrowRight size={14}/></Link></div></aside></div></section></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="field-label">{label}</span>{children}</label>}
function Info({icon,label,value,copy}:{icon:React.ReactNode;label:string;value:string;copy?:string}){return <div className="surface rounded-xl p-6"><div className="text-amber [&>svg]:h-5 [&>svg]:w-5">{icon}</div><div className="mt-7"><SpecLabel>{label}</SpecLabel><div className="mt-2 font-display text-xl font-bold">{value}</div>{copy&&<p className="body-copy mt-3 text-sm">{copy}</p>}</div></div>}
