import type{Metadata}from"next";
import Link from"next/link";
import{ArrowRight,MapPin}from"lucide-react";
import{PageHero,SectionIntro,SpecLabel}from"@/components/PublicUI";
export const metadata:Metadata={title:"About",description:"About Dragline 3D, a Louisville-based custom FDM additive manufacturing shop."};
export default function AboutPage(){return <div className="public-shell"><PageHero eyebrow="About Dragline" title="A direct path from model to" accent="physical part." copy="Dragline 3D is a Louisville-based additive manufacturing shop focused on practical FDM work, clear quoting, and straightforward communication." actions={<Link href="/quote" className="btn-primary">Get a Quote<ArrowRight size={15}/></Link>}/>
<section className="public-section"><div className="public-container"><SectionIntro eyebrow="The approach" title={<>Small shop. <span className="text-amber">Serious process.</span></>} copy="Dragline serves both organizations and individual customers without requiring a high-volume production commitment."/><div className="grid gap-4 lg:grid-cols-3"><AboutCard n="01" title="Focused scope">FDM prototypes, replacement parts, functional components, fixtures, and short runs using the materials and build area listed on this site.</AboutCard><AboutCard n="02" title="Visible workflow">Model upload, configuration, slicer-based pricing, payment, order updates, pickup or shipping—connected in one customer path.</AboutCard><AboutCard n="03" title="Honest fit">Dragline does not currently present itself as a resin, metal, or high-volume molding provider. If FDM is not a sensible process for the part, that matters.</AboutCard></div></div></section>
<section className="public-section bg-[#0e1011]"><div className="public-container grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><div className="eyebrow mb-5">The name</div><h2 className="display-lg">An anchor line.</h2></div><div className="space-y-6 body-lg"><p>A spider’s dragline is the strong silk thread that anchors the web and supports its weight. The name is also associated with heavy working cable. Both point toward the same idea: dependable parts made to serve a purpose.</p><div className="surface rounded-xl p-6"><div className="flex items-center gap-3 text-amber"><MapPin size={18}/><SpecLabel>Louisville, Kentucky</SpecLabel></div><p className="body-copy mt-4">Local pickup connects the digital quote process to a nearby manufacturing service, while shipping supports customers beyond the immediate area.</p></div></div></div></section></div>}
function AboutCard({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <article className="surface rounded-xl p-7"><SpecLabel>{n}</SpecLabel><h3 className="heading-md mt-8">{title}</h3><p className="body-copy mt-4">{children}</p></article>}
