import Link from"next/link";
import{ArrowRight,ArrowDownRight,Crosshair,Layers3,ScanLine,PackageCheck,MoveUpRight}from"lucide-react";
import{SpecLabel}from"@/components/PublicUI";
const uses=["Prototypes","Replacement parts","Fixtures & tooling","Functional parts","Short-run production"];
export default function Home(){return <div className="public-shell">
<section className="relative min-h-[calc(100svh-76px)] overflow-hidden border-b border-white/10"><div className="absolute inset-0 technical-grid opacity-70"/><div className="pointer-events-none absolute -right-24 top-1/2 hidden aspect-square w-[50vw] -translate-y-1/2 rounded-full border border-white/10 lg:block"><div className="absolute inset-[12%] rounded-full border border-amber/30"/><div className="absolute inset-[32%] rounded-full border border-dashed border-white/20"/><div className="absolute left-1/2 top-0 h-full w-px bg-white/10"/><div className="absolute left-0 top-1/2 h-px w-full bg-white/10"/><div className="absolute left-1/2 top-1/2 h-3 w-3 -translate-x-1/2 -translate-y-1/2 bg-amber"/></div>
<div className="relative grid min-h-[calc(100svh-76px)] lg:grid-cols-[minmax(0,1.35fr)_minmax(320px,.65fr)]"><div className="flex flex-col justify-between px-4 py-10 sm:px-8 lg:px-[max(2rem,calc((100vw-76rem)/2))] lg:pr-12 lg:py-14"><div className="flex items-center gap-4 font-mono text-[9px] uppercase tracking-[.2em] text-steel"><span className="h-px w-12 bg-amber"/>Custom additive manufacturing</div><div className="py-16 lg:py-10"><h1 className="font-display text-[clamp(4.2rem,11.5vw,10.5rem)] font-black uppercase leading-[.76] tracking-[-.06em]"><span className="block">Make the</span><span className="block text-amber">part.</span><span className="block text-bone/25">Keep moving.</span></h1><p className="body-lg mt-9 max-w-xl border-l border-amber pl-5">Functional FDM parts for teams and individuals who need a useful physical answer—not a novelty print.</p></div><div className="flex flex-col gap-4 border-t border-white/10 pt-6 sm:flex-row sm:items-center"><Link href="/quote" className="btn-primary px-7">Start a Quote<MoveUpRight size={16}/></Link><Link href="/capabilities" className="btn-quiet">See what we make<ArrowRight size={15}/></Link></div></div>
<aside className="relative hidden border-l border-white/10 lg:flex lg:flex-col lg:justify-end"><div className="relative z-10 border-t border-white/10 bg-[#0b0c0d]/85 p-8"><SpecLabel>Production envelope</SpecLabel><dl className="mt-6 divide-y divide-white/10">{[["Process","FDM"],["Build area","400 × 400 × 400 mm"],["Quote input","STL / 3MF"],["Location","Louisville, KY"]].map(([k,v])=><div key={k} className="flex justify-between gap-4 py-3"><dt className="text-xs text-steel">{k}</dt><dd className="font-mono text-xs text-bone">{v}</dd></div>)}</dl></div></aside></div></section>
<section className="border-b border-white/10 bg-bone text-[#121314]"><div className="public-container py-6"><div className="flex gap-8 overflow-x-auto font-display text-xl font-black uppercase sm:justify-between sm:text-2xl">{uses.map((u,i)=><div key={u} className="flex shrink-0 items-center gap-8"><span>{u}</span>{i<uses.length-1&&<span className="text-amber">/</span>}</div>)}</div></div></section>
<section className="overflow-hidden border-b border-white/10"><div className="public-container grid lg:grid-cols-[.72fr_1.28fr]"><div className="py-20 pr-8 lg:py-32"><div className="eyebrow">Where Dragline fits</div><h2 className="mt-8 font-display text-[clamp(3.2rem,6vw,6.2rem)] font-black uppercase leading-[.85] tracking-[-.05em]">Between an idea and a working object.</h2><p className="body-copy mt-8 max-w-md">Use the process for a first physical iteration, a hard-to-find replacement, a shop fixture, or a repeatable batch. The part and its application lead the conversation.</p><Link href="/capabilities" className="btn-secondary mt-8">Explore capabilities<ArrowRight size={15}/></Link></div><div className="border-t border-white/10 lg:border-l lg:border-t-0"><Story n="01" icon={<ScanLine/>} title="Resolve the geometry" copy="Upload a model, inspect it in the browser, and let the existing slicer calculate the manufacturing data behind the quote."/><Story n="02" icon={<Crosshair/>} title="Specify the outcome" copy="Choose material, layer quality, infill, and quantity around what the part needs to accomplish."/><Story n="03" icon={<Layers3/>} title="Produce with context" copy="The order carries its files and configuration forward into the Dragline production workflow."/></div></div></section>
<section className="relative overflow-hidden border-b border-white/10 bg-[#111315] py-24 sm:py-32"><div className="absolute inset-y-0 right-0 hidden w-2/5 border-l border-white/10 bg-[linear-gradient(135deg,transparent_49.8%,rgba(233,162,59,.16)_50%,transparent_50.2%)] lg:block"/><div className="public-container relative"><div className="max-w-4xl"><div className="eyebrow">Material decisions</div><h2 className="mt-8 font-display text-[clamp(3.5rem,8vw,8rem)] font-black uppercase leading-[.82] tracking-[-.055em]">Not every plastic behaves the same.</h2><p className="body-lg mt-8 max-w-2xl">Compare current standard, engineering, flexible, and fiber-reinforced options without pretending a material name alone guarantees part performance.</p><Link href="/materials" className="btn-primary mt-9">Open the material reference<ArrowRight size={15}/></Link></div></div></section>
<section className="border-b border-white/10"><div className="grid lg:grid-cols-2"><div className="relative min-h-[440px] overflow-hidden bg-[#0e1011] p-8 sm:p-12 lg:p-16"><div className="technical-grid absolute inset-0"/><div className="relative flex h-full flex-col justify-between"><div><SpecLabel>Work / 001</SpecLabel><h2 className="mt-6 display-lg">The proof is the output.</h2></div><div><p className="body-copy max-w-md">The portfolio draws only from Dragline’s existing gallery. No stock projects, invented customers, or fabricated case studies.</p><Link href="/gallery" className="btn-secondary mt-6">View Our Work<ArrowDownRight size={16}/></Link></div></div></div><div className="flex min-h-[440px] items-end bg-amber p-8 text-[#15100a] sm:p-12 lg:p-16"><div><SpecLabel>Ready to build</SpecLabel><h2 className="mt-6 font-display text-[clamp(3.4rem,7vw,7rem)] font-black uppercase leading-[.82] tracking-[-.05em]">Your model starts the process.</h2><div className="mt-9 flex flex-wrap gap-3"><Link href="/quote" className="min-h-12 bg-[#111315] px-6 py-3 font-display font-black uppercase text-bone">Get a Quote</Link><Link href="/contact" className="min-h-12 border border-black/30 px-6 py-3 font-display font-black uppercase">Discuss the job</Link></div></div></div></div></section>
<section className="py-16"><div className="public-container flex flex-col justify-between gap-7 sm:flex-row sm:items-center"><div><SpecLabel>Also available</SpecLabel><h2 className="mt-3 heading-md">Published, ready-made designs.</h2></div><Link href="/catalog" className="btn-quiet">Browse the secondary shop channel<ArrowRight size={15}/></Link></div></section>
</div>}
function Story({n,icon,title,copy}:{n:string;icon:React.ReactNode;title:string;copy:string}){return <article className="group grid min-h-[230px] grid-cols-[70px_1fr] border-b border-white/10 last:border-b-0 sm:grid-cols-[100px_1fr]"><div className="flex flex-col items-center justify-between border-r border-white/10 py-7 text-amber"><span className="font-mono text-[10px] text-steel">{n}</span>{icon}</div><div className="flex flex-col justify-center p-7 sm:p-10"><h3 className="font-display text-3xl font-black uppercase sm:text-4xl">{title}</h3><p className="body-copy mt-4 max-w-xl">{copy}</p></div></article>}
