import Link from "next/link";
import { ArrowRight, Upload, SlidersHorizontal, CreditCard, PackageCheck, Wrench, Boxes, Repeat2, Ruler, ShoppingBag } from "lucide-react";
import { SectionIntro, SpecLabel } from "@/components/PublicUI";
const capabilities = [
  { icon:<Wrench size={20}/>, title:"Functional parts", copy:"Brackets, enclosures, adapters, and components intended to do a job—not just sit on a shelf." },
  { icon:<Ruler size={20}/>, title:"Prototypes", copy:"Physical iterations for checking fit, form, assembly, and design direction before committing to production." },
  { icon:<Repeat2 size={20}/>, title:"Replacement parts", copy:"Custom replacements when the original part is unavailable, discontinued, or worth improving." },
  { icon:<Boxes size={20}/>, title:"Fixtures & short runs", copy:"Jigs, shop aids, fixtures, and repeatable batches up to the scale supported by the current FDM process." },
];
const steps = [
  {n:"01",icon:<Upload size={18}/>,title:"Upload",copy:"Send an STL or 3MF and confirm the model in the browser."},
  {n:"02",icon:<SlidersHorizontal size={18}/>,title:"Configure",copy:"Select material, quality, infill, quantity, and delivery preferences."},
  {n:"03",icon:<CreditCard size={18}/>,title:"Review",copy:"See pricing based on slicer output, then approve and pay securely."},
  {n:"04",icon:<PackageCheck size={18}/>,title:"Receive",copy:"Choose Louisville pickup or shipping when available for your order."},
];
export default function Home() { return <div className="public-shell">
  <section className="relative overflow-hidden border-b border-white/10"><div className="technical-grid absolute inset-0"/><div className="public-container relative py-14 sm:py-20 lg:py-28">
    <div className="mb-8 flex flex-wrap items-center justify-between gap-3 font-mono text-[10px] uppercase tracking-[.17em] text-steel"><span>Custom FDM additive manufacturing</span><span className="flex items-center gap-2"><span className="status-dot"/>Louisville, Kentucky</span></div>
    <h1 className="display-xl max-w-6xl">Parts built<br/><span className="text-amber">for real use.</span></h1>
    <div className="mt-9 grid gap-8 border-t border-white/10 pt-8 lg:grid-cols-[1fr_.72fr] lg:items-end"><div><p className="body-lg max-w-2xl">Custom additive manufacturing for prototypes, replacement parts, fixtures, and short production runs. Upload your model and build a quote from real slicer data.</p><div className="mt-8 flex flex-col gap-3 min-[420px]:flex-row"><Link href="/quote" className="btn-primary">Get a Quote<ArrowRight size={16}/></Link><Link href="/capabilities" className="btn-secondary">View Capabilities</Link></div></div>
      <div className="surface-raised rounded-xl p-5 sm:p-6"><SpecLabel>Current process</SpecLabel><div className="mt-5 grid grid-cols-2 gap-px overflow-hidden rounded-md bg-white/10"><Metric value="FDM" label="Process"/><Metric value="400 × 400 × 400" label="Build area (mm)"/><Metric value="STL / 3MF" label="Quote files"/><Metric value="1–100" label="Typical quantity"/></div></div>
    </div>
  </div></section>
  <section className="public-section"><div className="public-container"><SectionIntro eyebrow="What we make" title={<>Built around the <span className="text-amber">part.</span></>} copy="Dragline focuses on practical FDM work for businesses, teams, and individuals who need a physical component made clearly and efficiently." action={{href:"/capabilities",label:"Explore capabilities"}}/><div className="grid gap-4 md:grid-cols-2">{capabilities.map((c,i)=><article key={c.title} className="surface group rounded-xl p-6 sm:p-8"><div className="flex items-start justify-between"><span className="text-amber">{c.icon}</span><SpecLabel>0{i+1}</SpecLabel></div><h3 className="heading-md mt-9">{c.title}</h3><p className="body-copy mt-4 max-w-md">{c.copy}</p></article>)}</div></div></section>
  <section className="public-section bg-[#0e1011]"><div className="public-container"><SectionIntro eyebrow="A clear path to production" title={<>From model to <span className="text-amber">finished part.</span></>} copy="The existing quote system combines model review, configuration, slicer output, payment, and fulfillment in one continuous workflow."/><div className="grid gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{steps.map(s=><article key={s.n} className="bg-[#111315] p-6 lg:min-h-64"><div className="flex items-center justify-between text-amber">{s.icon}<span className="font-mono text-xs text-steel">{s.n}</span></div><h3 className="mt-12 font-display text-2xl font-extrabold">{s.title}</h3><p className="body-copy mt-3 text-sm">{s.copy}</p></article>)}</div></div></section>
  <section className="public-section"><div className="public-container"><SectionIntro eyebrow="Materials" title={<>Choose for the <span className="text-amber">application.</span></>} copy="The current material range spans straightforward prototypes, flexible parts, weather-facing components, and reinforced functional prints. Final suitability depends on part geometry and use." action={{href:"/materials",label:"Compare materials"}}/><div className="grid gap-4 sm:grid-cols-3"><MaterialGroup label="General purpose" names="PLA · Pro PCTG · TPU"/><MaterialGroup label="Engineering" names="ABS · ASA · PET-GF15 · PETG-ESD · Nylon"/><MaterialGroup label="Reinforced" names="ASA-CF · PETG-CF · PA-CF · PAHT-CF · PET-CF"/></div></div></section>
  <section className="public-section-sm bg-[#e9a23b] text-[#17120b]"><div className="public-container grid gap-7 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] opacity-65">Ready when your model is</div><h2 className="mt-3 font-display text-4xl font-black uppercase leading-none sm:text-5xl">Start with the part you need.</h2><p className="mt-4 max-w-2xl text-sm leading-6 opacity-75">Upload an STL or 3MF to configure a quote, or contact Dragline for an unusual project.</p></div><div className="flex flex-col gap-3 min-[420px]:flex-row"><Link href="/quote" className="min-h-11 rounded-md bg-[#111315] px-5 py-3 text-center font-display text-sm font-extrabold uppercase text-bone">Get a Quote</Link><Link href="/contact" className="min-h-11 rounded-md border border-black/30 px-5 py-3 text-center font-display text-sm font-extrabold uppercase">Discuss a Project</Link></div></div></section>
  <section className="public-section-sm"><div className="public-container grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div className="flex gap-4"><ShoppingBag className="mt-1 text-amber"/><div><h2 className="heading-md">Ready-made designs are here, too.</h2><p className="body-copy mt-3 max-w-xl">The shop remains available as a secondary path for published catalog designs, each routed through the same quote workflow.</p></div></div><Link href="/catalog" className="btn-secondary">Browse the Shop<ArrowRight size={15}/></Link></div></section>
</div>; }
function Metric({value,label}:{value:string;label:string}) { return <div className="bg-[#121416] p-4"><div className="font-mono text-sm font-semibold text-bone">{value}</div><div className="mt-2 font-mono text-[9px] uppercase tracking-[.14em] text-steel">{label}</div></div>; }
function MaterialGroup({label,names}:{label:string;names:string}) { return <div className="surface rounded-xl p-6"><SpecLabel>{label}</SpecLabel><p className="mt-7 font-display text-2xl font-extrabold leading-tight">{names}</p></div>; }
