"use client";
import{useEffect,useState}from"react";
import Link from"next/link";
import{ArrowUpRight}from"lucide-react";
type Gallery={id:string;title:string;material:string;notes:string|null;image_url:string|null;video_url:string|null};
type Product={id:string;title:string;category:string|null;description:string|null;image_url:string|null};
export function HomeLiveMedia(){const[g,setG]=useState<Gallery[]>([]),[p,setP]=useState<Product[]>([]),[done,setDone]=useState(false);useEffect(()=>{Promise.all([fetch("/api/gallery").then(r=>r.ok?r.json():[]),fetch("/api/catalog").then(r=>r.ok?r.json():[])]).then(([a,b])=>{setG((Array.isArray(a)?a:[]).filter(x=>x.image_url).slice(0,3));setP((Array.isArray(b)?b:[]).filter(x=>x.image_url).slice(0,2))}).finally(()=>setDone(true))},[]);const media=[...g.map(x=>({...x,kind:"Work",href:"/gallery",meta:x.material})),...p.map(x=>({...x,kind:"Shop",href:"/catalog",meta:x.category||"Made to order"}))];if(!done)return <section className="media-stage border-b border-white/10" aria-label="Loading Dragline work"><div className="h-[70svh] min-h-[520px] animate-pulse bg-[#101214]"/></section>;if(!media.length)return <section className="border-b border-white/10"><div className="public-container grid gap-8 py-24 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><div className="eyebrow">Work / Shop</div><h2 className="mt-7 display-lg">The frame is ready for real Dragline media.</h2></div><p className="body-copy">Gallery projects and published products will automatically become the visual story here as media is added through the existing admin tools.</p></div></section>;return <section className="border-b border-white/10"><header className="public-container grid gap-6 py-16 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="eyebrow">Made at Dragline</div><h2 className="mt-6 display-lg">Practical. Personal. Printed.</h2></div><p className="body-copy max-w-md">Live work and products from the existing Dragline gallery and catalog.</p></header><div className="grid auto-rows-[280px] sm:auto-rows-[360px] lg:grid-cols-12 lg:auto-rows-[340px]">{media.map((x,i)=><Link key={`${x.kind}-${x.id}`} href={x.href} className={`media-tile group relative overflow-hidden border-r border-t border-white/10 ${i===0?"lg:col-span-8 lg:row-span-2":"lg:col-span-4"}`}><img src={x.image_url!} alt={x.title} loading={i?"lazy":"eager"} className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-[1.035]"/><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/5 to-black/10"/><div className="absolute inset-x-0 bottom-0 flex items-end justify-between gap-4 p-5 sm:p-7"><div><span className="font-mono text-[9px] uppercase tracking-[.16em] text-amber">{x.kind} / {x.meta}</span><h3 className={`mt-2 font-display font-black uppercase leading-none ${i===0?"text-4xl sm:text-6xl":"text-3xl"}`}>{x.title}</h3></div><span className="flex h-11 w-11 shrink-0 items-center justify-center border border-white/30 bg-black/25 backdrop-blur"><ArrowUpRight size={18}/></span></div></Link>)}</div></section>}

export function CapabilityMediaBand(){const[items,setItems]=useState<Gallery[]>([]);useEffect(()=>{fetch("/api/gallery").then(r=>r.ok?r.json():[]).then(d=>setItems((Array.isArray(d)?d:[]).filter(x=>x.image_url).slice(0,3))).catch(()=>{})},[]);if(!items.length)return null;return <section className="grid min-h-[440px] border-b border-white/10 md:grid-cols-3">{items.map((x,i)=><figure key={x.id} className="group relative min-h-[380px] overflow-hidden border-r border-white/10"><img src={x.image_url!} alt={x.title} loading="lazy" className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-[1.035]"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent"/><figcaption className="absolute inset-x-0 bottom-0 p-6"><span className="font-mono text-[9px] uppercase tracking-[.15em] text-amber">{x.material}</span><div className="mt-2 font-display text-2xl font-black uppercase">{x.title}</div></figcaption></figure>)}</section>}
