"use client";
import Link from "next/link";
import {usePathname}from"next/navigation";
import{useEffect,useState}from"react";
import{Menu,X,ArrowUpRight}from"lucide-react";
import{DraglineMark}from"./DraglineMark";
const links=[["/capabilities","Capabilities"],["/materials","Materials"],["/gallery","Our Work"],["/catalog","Shop"]] as const;
export function Nav(){const pathname=usePathname();const[open,setOpen]=useState(false);useEffect(()=>setOpen(false),[pathname]);return <header className="sticky top-0 z-50 border-b border-white/10 bg-[#090a0b]/95 backdrop-blur-xl"><div className="grid h-[76px] grid-cols-[1fr_auto] lg:grid-cols-[280px_1fr_auto]">
<Link href="/" className="flex items-center gap-3 border-r border-white/10 px-4 sm:px-7" aria-label="Dragline 3D home"><DraglineMark size={32}/><div><div className="font-display text-lg font-black tracking-tight">DRAGLINE<span className="text-amber">/</span>3D</div><div className="font-mono text-[7px] uppercase tracking-[.22em] text-steel">Louisville / Kentucky</div></div></Link>
<nav className="hidden items-stretch lg:flex" aria-label="Primary navigation">{links.map(([href,label],i)=><Link key={href} href={href} className={`group flex min-w-[120px] items-center justify-center border-r border-white/[.07] px-5 text-xs font-semibold uppercase tracking-[.08em] transition-colors ${pathname.startsWith(href)?"bg-white/[.05] text-amber":"text-bone/55 hover:bg-white/[.03] hover:text-bone"}`}><span className="mr-2 font-mono text-[8px] text-steel">0{i+1}</span>{label}</Link>)}</nav>
<div className="hidden items-center gap-2 px-5 lg:flex"><Link href="/account" className="btn-quiet text-xs">Account</Link><Link href="/quote" className="btn-primary">Start a Quote<ArrowUpRight size={15}/></Link></div>
<button className="m-4 flex h-11 w-11 items-center justify-center border border-white/15 lg:hidden" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-controls="mobile-menu" aria-label={open?"Close navigation":"Open navigation"}>{open?<X/>:<Menu/>}</button></div>
{open&&<nav id="mobile-menu" className="border-t border-white/10 bg-[#090a0b] lg:hidden"><div className="grid grid-cols-2">{links.map(([href,label],i)=><Link key={href} href={href} className="flex min-h-20 flex-col justify-between border-b border-r border-white/10 p-4"><span className="font-mono text-[9px] text-steel">0{i+1}</span><span className="font-display text-xl font-bold">{label}</span></Link>)}<Link href="/account" className="flex min-h-16 items-center border-r border-white/10 px-4 font-semibold">Account</Link><Link href="/quote" className="flex min-h-16 items-center justify-between bg-amber px-4 font-display font-black uppercase text-[#15100a]">Get a Quote<ArrowUpRight size={17}/></Link></div></nav>}</header>}
