"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, Play, Facebook, Images } from "lucide-react";
import { PageHero, EmptyState, LoadingGrid, SpecLabel } from "@/components/PublicUI";
type GalleryItem={id:string;title:string;client:string|null;material:string;notes:string|null;image_url:string|null;video_url:string|null;sort_order:number};
export default function GalleryPage(){const[items,setItems]=useState<GalleryItem[]>([]);const[loading,setLoading]=useState(true);const[failed,setFailed]=useState(false);useEffect(()=>{fetch("/api/gallery").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>setItems(Array.isArray(d)?d:[])).catch(()=>setFailed(true)).finally(()=>setLoading(false))},[]);return <div className="public-shell">
<PageHero eyebrow="Our Work" title="Real output from the" accent="Dragline process." copy="A growing record of parts produced through Dragline 3D. Project details appear only where they have been added to the existing gallery." actions={<a href="https://www.facebook.com/dragline3d" target="_blank" rel="noopener noreferrer" className="btn-secondary"><Facebook size={15}/>Facebook</a>}/>
<section className="public-section"><div className="public-container">{loading?<LoadingGrid/>:failed?<EmptyState icon={<Images size={30}/>} title="The gallery could not be loaded" copy="Please try again shortly or visit the Dragline Facebook page for recent work."/>:items.length===0?<EmptyState icon={<Images size={30}/>} title="Work is being documented" copy="The gallery is ready for real Dragline project media. No placeholder projects or customer stories have been fabricated."/>:<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{items.map((p,i)=><article key={p.id} className="surface overflow-hidden rounded-xl group"><div className="relative aspect-[4/3] overflow-hidden bg-[#0e1011]">{p.image_url?<img src={p.image_url} alt={p.title} loading="lazy" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.03]"/>:p.video_url?<a href={p.video_url} target="_blank" rel="noopener noreferrer" className="flex h-full items-center justify-center" aria-label={`Watch ${p.title}`}><span className="flex h-14 w-14 items-center justify-center rounded-full border border-amber/40 bg-amber/10 text-amber"><Play size={22}/></span></a>:<div className="flex h-full items-center justify-center"><Images className="text-steel/30" size={38}/></div>}<div className="absolute left-3 top-3 rounded bg-[#0b0c0d]/85 px-2 py-1"><SpecLabel>{String(i+1).padStart(2,"0")}</SpecLabel></div><div className="absolute right-3 top-3 rounded bg-amber px-2 py-1 font-mono text-[9px] font-bold uppercase tracking-wider text-[#17120b]">{p.material}</div></div><div className="p-6"><h2 className="font-display text-2xl font-black">{p.title}</h2>{p.client&&<div className="mt-2 font-mono text-[9px] uppercase tracking-[.16em] text-amber">{p.client}</div>}{p.notes&&<p className="body-copy mt-4 text-sm">{p.notes}</p>}</div></article>)}</div>}
<div className="mt-14 flex flex-col items-start justify-between gap-6 border-t border-white/10 pt-8 sm:flex-row sm:items-center"><div><h2 className="heading-md">Have a part in mind?</h2><p className="body-copy mt-2">Start with your own model or contact Dragline to discuss the project.</p></div><Link href="/quote" className="btn-primary">Get a Quote<ArrowRight size={15}/></Link></div></div></section></div>}
