"use client";
export const runtime="edge";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
import {ArrowRight,Box,ShoppingBag} from "lucide-react";
import {PageHero,EmptyState,LoadingGrid,SpecLabel} from "@/components/PublicUI";
type CatalogItem={id:string;title:string;description:string|null;category:string|null;file_url:string;file_name:string;image_url:string|null;published:boolean;sort_order:number};
export default function PublicCatalog(){const[items,setItems]=useState<CatalogItem[]>([]);const[loading,setLoading]=useState(true);const[failed,setFailed]=useState(false);const[category,setCategory]=useState("All");const router=useRouter();useEffect(()=>{fetch("/api/catalog").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>setItems(Array.isArray(d)?d:[])).catch(()=>setFailed(true)).finally(()=>setLoading(false))},[]);const categories=useMemo(()=>["All",...Array.from(new Set(items.flatMap(i=>i.category?[i.category]:[]))).sort()], [items]);const filtered=category==="All"?items:items.filter(i=>i.category===category);return <div className="public-shell">
<PageHero eyebrow="Shop / Made to order" title="Find something" accent="worth printing." copy="Novelty pieces, decorations, gifts, collectibles, and other ready-to-order designs belong at Dragline just as much as functional work. Browse the real published catalog, then configure your selection through the existing quote workflow." actions={<Link href="/quote" className="btn-secondary">Have your own idea?</Link>}/>
<section className="border-t border-white/10"><div className="sticky top-[76px] z-30 border-b border-white/10 bg-[#0b0c0d]/95 backdrop-blur"><div className="public-container flex gap-1 overflow-x-auto py-3" aria-label="Shop categories">{categories.map((c,i)=><button key={c} onClick={()=>setCategory(c)} className={`min-h-11 whitespace-nowrap border px-4 font-mono text-[10px] uppercase tracking-[.13em] transition ${category===c?"border-amber bg-amber text-[#17120b]":"border-transparent text-bone/50 hover:border-white/20 hover:text-bone"}`}><span className="mr-2 opacity-50">{String(i+1).padStart(2,"0")}</span>{c}</button>)}</div></div><div className="public-container py-16 lg:py-24">
{loading?<LoadingGrid/>:failed?<EmptyState icon={<ShoppingBag size={30}/>} title="The shop could not be loaded" copy="Please try again shortly. Custom quote uploads remain available."/>:filtered.length===0?<EmptyState icon={<ShoppingBag size={30}/>} title="No designs in this category yet" copy="Published catalog items will appear here. You can still upload a custom model for a quote."/>:<div className="grid gap-px overflow-hidden border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-12">{filtered.map((item,i)=><article key={item.id} className={`group flex flex-col bg-[#0b0c0d] ${i===0&&filtered.length>2?"lg:col-span-8 lg:row-span-2":"lg:col-span-4"}`}><div className={`relative overflow-hidden bg-[#0e1011] ${i===0&&filtered.length>2?"aspect-[16/10] lg:aspect-auto lg:min-h-[620px]":"aspect-[4/5]"}`}>{item.image_url?<img src={item.image_url} alt={item.title} loading={i?"lazy":"eager"} className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.035]"/>:<div className="technical-grid flex h-full flex-col items-center justify-center gap-3 text-steel/30"><Box size={36}/><SpecLabel>No preview</SpecLabel></div>}{item.category&&<span className="absolute left-4 top-4 border border-white/20 bg-[#0b0c0d]/85 px-2 py-1 font-mono text-[9px] uppercase tracking-[.14em] text-amber backdrop-blur">{item.category}</span>}<div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/90 to-transparent p-5 pt-20"><h2 className={`font-display font-black uppercase leading-none ${i===0&&filtered.length>2?"text-4xl sm:text-6xl":"text-3xl"}`}>{item.title||"Untitled design"}</h2>{item.description&&<p className="mt-3 line-clamp-2 max-w-xl text-sm leading-6 text-bone/65">{item.description}</p>}<button onClick={()=>router.push(`/quote?catalog=${item.id}`)} className="mt-5 inline-flex min-h-11 items-center gap-2 border border-white/30 bg-black/25 px-4 font-display text-xs font-black uppercase text-bone backdrop-blur transition hover:border-amber hover:text-amber">Configure & Quote<ArrowRight size={14}/></button></div></div></article>)}</div>}
<div className="mt-12 border-t border-white/10 pt-7"><p className="font-mono text-[10px] uppercase tracking-[.13em] text-steel">Catalog items are made to order. Current quote-system pricing and minimums apply.</p></div></div></section></div>}
