"use client";
export const runtime="edge";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
import {ArrowRight,Box,ShoppingBag} from "lucide-react";
import {PageHero,EmptyState,LoadingGrid,SpecLabel} from "@/components/PublicUI";
type CatalogItem={id:string;title:string;description:string|null;category:string|null;file_url:string;file_name:string;image_url:string|null;published:boolean;sort_order:number};
export default function PublicCatalog(){const[items,setItems]=useState<CatalogItem[]>([]);const[loading,setLoading]=useState(true);const[failed,setFailed]=useState(false);const[category,setCategory]=useState("All");const router=useRouter();useEffect(()=>{fetch("/api/catalog").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>setItems(Array.isArray(d)?d:[])).catch(()=>setFailed(true)).finally(()=>setLoading(false))},[]);const categories=useMemo(()=>["All",...Array.from(new Set(items.flatMap(i=>i.category?[i.category]:[]))).sort()], [items]);const filtered=category==="All"?items:items.filter(i=>i.category===category);return <div className="public-shell">
<PageHero eyebrow="Shop / Made to order" title="Find something" accent="worth printing." copy="Novelty pieces, decorations, gifts, collectibles, and other ready-to-order designs belong at Dragline just as much as functional work. Browse the real published catalog, then configure your selection through the existing quote workflow." actions={<Link href="/quote" className="btn-secondary">Have your own idea?</Link>}/>
<section className="public-section"><div className="public-container">{categories.length>1&&<div className="mb-9 flex gap-2 overflow-x-auto pb-2" aria-label="Shop categories">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`min-h-11 whitespace-nowrap rounded-md border px-4 font-mono text-[10px] uppercase tracking-[.13em] ${category===c?"border-amber bg-amber text-[#17120b]":"border-white/15 text-bone/60 hover:border-white/30 hover:text-bone"}`}>{c}</button>)}</div>}
{loading?<LoadingGrid/>:failed?<EmptyState icon={<ShoppingBag size={30}/>} title="The shop could not be loaded" copy="Please try again shortly. Custom quote uploads remain available."/>:filtered.length===0?<EmptyState icon={<ShoppingBag size={30}/>} title="No designs in this category yet" copy="Published catalog items will appear here. You can still upload a custom model for a quote."/>:<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(item=><article key={item.id} className="surface flex overflow-hidden rounded-xl flex-col"><div className="relative aspect-[4/3] bg-[#0e1011]">{item.image_url?<img src={item.image_url} alt={item.title} loading="lazy" className="h-full w-full object-cover"/>:<div className="flex h-full flex-col items-center justify-center gap-3 text-steel/30"><Box size={36}/><SpecLabel>No preview</SpecLabel></div>}{item.category&&<span className="absolute right-3 top-3 rounded bg-[#0b0c0d]/90 px-2 py-1 font-mono text-[9px] uppercase tracking-[.14em] text-amber">{item.category}</span>}</div><div className="flex flex-1 flex-col p-6"><h2 className="font-display text-2xl font-black">{item.title||"Untitled design"}</h2>{item.description&&<p className="body-copy mt-3 line-clamp-3 text-sm">{item.description}</p>}<button onClick={()=>router.push(`/quote?catalog=${item.id}`)} className="btn-primary mt-7 w-full">Configure & Quote<ArrowRight size={14}/></button></div></article>)}</div>}
<div className="mt-12 border-t border-white/10 pt-7"><p className="font-mono text-[10px] uppercase tracking-[.13em] text-steel">Catalog items are made to order. Current quote-system pricing and minimums apply.</p></div></div></section></div>}
