import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Box, Ruler, Wrench, Repeat2, Layers3, Maximize } from "lucide-react";
import { PageHero, SectionIntro, SpecLabel } from "@/components/PublicUI";
export const metadata:Metadata={title:"Capabilities",description:"Explore Dragline 3D capabilities for functional FDM parts, prototypes, replacement components, fixtures, and short production runs."};
const items=[
  {icon:<Box/>,title:"Functional parts",copy:"Custom brackets, adapters, housings, organizers, and other components where fit and practical use matter."},
  {icon:<Ruler/>,title:"Prototypes",copy:"Physical models for evaluating shape, scale, interfaces, and assembly before the next design decision."},
  {icon:<Repeat2/>,title:"Replacement parts",copy:"One-off replacements and revised components produced from a customer-supplied model or a project discussed with Dragline."},
  {icon:<Wrench/>,title:"Fixtures & tooling",copy:"Jigs, alignment aids, holders, templates, and shop tools suited to the available FDM materials and process."},
  {icon:<Layers3/>,title:"Short-run production",copy:"Repeatable batches for projects that need more than a prototype without moving directly to high-volume tooling."},
  {icon:<Maximize/>,title:"Large-format FDM",copy:"A 400 × 400 × 400 mm build area supports larger single parts or efficient layouts of smaller components."},
];
export default function CapabilitiesPage(){return <div className="public-shell"><PageHero eyebrow="Capabilities" title="A practical process for" accent="functional work." copy="Dragline 3D produces custom FDM parts for real applications—from the first physical prototype through short repeatable runs." actions={<><Link href="/quote" className="btn-primary">Get a Quote<ArrowRight size={15}/></Link><Link href="/gallery" className="btn-secondary">See Our Work</Link></>}/>
<section className="public-section"><div className="public-container"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{items.map((x,i)=><article key={x.title} className="surface rounded-xl p-7"><div className="flex justify-between text-amber">{x.icon}<SpecLabel>0{i+1}</SpecLabel></div><h2 className="heading-md mt-10">{x.title}</h2><p className="body-copy mt-4">{x.copy}</p></article>)}</div></div></section>
<section className="public-section bg-[#0e1011]"><div className="public-container"><SectionIntro eyebrow="Working envelope" title={<>Know the constraints <span className="text-amber">up front.</span></>} copy="FDM is a strong fit for many practical parts, but it is not the right process for every geometry or application. Dragline reviews the submitted model and selected configuration before production."/><div className="grid gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{[["400 × 400 × 400 mm","Build area"],["STL and 3MF","Direct quote formats"],["STEP","Conversion supported"],["FDM","Current print process"]].map(([v,l])=><div key={l} className="bg-[#111315] p-6"><div className="font-mono text-lg font-semibold text-bone">{v}</div><div className="mt-3 font-mono text-[9px] uppercase tracking-[.16em] text-steel">{l}</div></div>)}</div><div className="mt-8 rounded-xl border border-amber/20 bg-amber/[.06] p-6"><h3 className="font-display text-xl font-bold">Not sure whether FDM fits the job?</h3><p className="body-copy mt-2 max-w-3xl">Send the file and intended use. Dragline can discuss the project without promising performance that the geometry, material, or process cannot support.</p><Link href="/contact" className="btn-quiet mt-4 text-amber">Discuss the project<ArrowRight size={14}/></Link></div></div></section></div>}
