import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { PageHero, SectionIntro, SpecLabel } from "@/components/PublicUI";
export const metadata:Metadata={title:"Materials",description:"Compare the FDM materials currently offered by Dragline 3D for prototypes and functional printed parts."};
const groups=[
  {name:"General purpose",note:"Accessible choices for prototypes and everyday parts.",items:[{n:"PLA",d:"A stiff, straightforward option for visual models, fit checks, and many indoor parts."},{n:"Pro PCTG",d:"A durable general-purpose material offered for parts needing more toughness than typical prototype material."},{n:"TPU",d:"A flexible option for grips, bumpers, protective features, and parts that need controlled compliance."}]},
  {name:"Engineering",note:"Options for applications with more specific environmental or mechanical needs.",items:[{n:"ABS",d:"A familiar engineering plastic for functional parts where its processing and material characteristics fit the application."},{n:"ASA",d:"A weather-oriented option commonly selected for outdoor-facing parts and housings."},{n:"PET-GF15",d:"Glass-fiber-reinforced PET for parts where stiffness and dimensional stability are priorities."},{n:"PETG-ESD",d:"An electrostatic-dissipative option for appropriate electronics-handling applications."},{n:"PA (Nylon)",d:"A wear-oriented, tough material for appropriate moving, flexing, or load-bearing part designs."}]},
  {name:"Fiber reinforced",note:"Composite filaments for increased stiffness and controlled dimensional behavior.",items:[{n:"ASA-CF",d:"Carbon-fiber-reinforced ASA for stiff parts with a subdued technical finish."},{n:"PETG-CF",d:"A reinforced PETG option balancing practical durability and added stiffness."},{n:"PA-CF",d:"Carbon-fiber-reinforced nylon for demanding functional geometry when moisture and processing requirements are accounted for."},{n:"PAHT-CF",d:"A higher-temperature nylon composite available for projects that justify its added material requirements."},{n:"PET-CF",d:"Carbon-fiber-reinforced PET offered for stiff, dimensionally focused functional parts."}]},
];
export default function MaterialsPage(){return <div className="public-shell"><PageHero eyebrow="Materials" title="Material follows" accent="application." copy="Dragline supports a focused range of standard, engineering, and reinforced FDM materials. Selection should account for environment, loading, geometry, finish, and budget." actions={<Link href="/quote" className="btn-primary">Configure a Quote<ArrowRight size={15}/></Link>}/>
<section className="public-section"><div className="public-container"><SectionIntro eyebrow="Current range" title={<>Clear choices, <span className="text-amber">careful claims.</span></>} copy="These descriptions are general guidance—not a certification of part performance. Ask about the intended use when the choice is not obvious."/>
<div className="space-y-12">{groups.map((g,gi)=><section key={g.name}><div className="mb-5 grid gap-2 border-b border-white/10 pb-5 sm:grid-cols-[1fr_2fr] sm:items-end"><div><SpecLabel>0{gi+1}</SpecLabel><h2 className="mt-2 font-display text-3xl font-black uppercase">{g.name}</h2></div><p className="body-copy">{g.note}</p></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{g.items.map(x=><article key={x.n} className="surface rounded-xl p-6"><div className="h-1 w-10 bg-amber"/><h3 className="mt-7 font-display text-3xl font-black">{x.n}</h3><p className="body-copy mt-4">{x.d}</p></article>)}</div></section>)}</div>
<div className="mt-12 rounded-xl border border-white/10 bg-[#0e1011] p-6 sm:p-8"><h2 className="heading-md">Material availability and suitability</h2><p className="body-copy mt-4 max-w-3xl">Some reinforced materials may be ordered per job and can add lead time. Pricing remains controlled by the existing quote system. Final part performance depends on geometry, print orientation, settings, and real operating conditions.</p><Link href="/contact" className="btn-secondary mt-6">Ask about a material</Link></div></div></section></div>}
